### PR TITLE
Fix: User defined query

### PR DESCRIPTION
**Pull request by ashalfarhan**
### Background
Related to: #9

### CODE REVIEW

**Review by sandip2224 — CHANGES_REQUESTED** [review]
Looks good!! Could you do the same for remaining routes as well?

**Comment by ashalfarhan** [comment]
> Looks good!! Could you do the same for remaining routes as well? I'll be happy to merge it ASAP

Which query should be changed?

**Comment by sandip2224** [comment]
> > Looks good!! Could you do the same for remaining routes as well? I'll be happy to merge it ASAP
> 
> Which query should be changed?

You'll find the queries inside the JS files present [here.](https://github.com/sandip2224/RESTful-Ecommmerce-API/tree/master/api/routes)

**Comment by ashalfarhan** [comment]
> > > Looks good!! Could you do the same for remaining routes as well? I'll be happy to merge it ASAP
> > 
> > 
> > Which query should be changed?
> 
> You'll find the queries inside the JS files present [here.](https://github.com/sandip2224/RESTful-Ecommmerce-API/tree/master/api/routes)

Is that the query with id is automatically throw an error when it's not actually an `ObjectId` ?

**Comment by sandip2224** [comment]
Let it be, the user queries are more than fine.

**Pull request merged**
